services:
  - type: web
    name: cdn-app
    env: docker
    plan: free
    envVars:
      - key: HF_REPO_ID
        value: notamitgamer/cdn
      - key: HF_TOKEN
        sync: false
      - key: RAW_DOMAIN
        value: raw.cdn.amit.is-a.dev
      - key: RAW_BASE_URL
        value: https://raw.cdn.amit.is-a.dev
